name: Upload dotnet package

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          source-url: https://nuget.pkg.github.com/hgirish/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release github-actions-demo
      - name: Create the package
        run: dotnet pack --configuration Release github-actions-demo
      - name: Publish the package to GPR
        run: dotnet nuget push github-actions-demo/bin/Release/*.nupkg
