# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        cache: true
        
    - name: Display dotnet version
      run: dotnet --version
      
    - name: Install Dependencies
      run: dotnet add package Newtonsoft.Json
      
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults-9.0x"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-9.0.x
        path: TestResults-9.0.x
        # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always()}}
        
